/* q3ide_capture.h — Auto-generated by cbindgen. Do not edit. */

#ifndef Q3IDE_CAPTURE_H
#define Q3IDE_CAPTURE_H

/* WARNING: This file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Special window ID used for desktop capture (all displays composited).
 * Use this ID with q3ide_get_frame to retrieve the composited desktop frame.
 */
#define Q3ideQ3IDE_DESKTOP_CAPTURE_ID 4294967295

/**
 * Consecutive empty-crop frames before detector fires.
 * Empty crop = display stream is live but window rect produced zero pixels
 * (coordinates mismatch or window moved off-screen).
 */
#define Q3ideDETECTOR_EMPTY_THRESHOLD 20

/**
 * Consecutive dark frames before detector fires.
 * Dark = crop succeeded but all sampled pixels are near-black — GPU content
 * not composited into the display frame (Safari-class apps).
 */
#define Q3ideDETECTOR_DARK_THRESHOLD 30

/**
 * Pixel brightness threshold for "dark" detection (per channel, 0-255).
 * If all sampled pixels have R, G, B all below this value → dark frame.
 */
#define Q3ideDETECTOR_DARK_PIXEL_MAX 12

/**
 * Special window ID for desktop capture (all displays composited).
 */
#define Q3ideDESKTOP_CAPTURE_ID 4294967295

/**
 * Error codes returned by C-ABI functions.
 */
typedef enum Q3ideQ3ideError {
    Q3IDE_Q3IDE_ERROR_OK = 0,
    Q3IDE_Q3IDE_ERROR_NOT_AVAILABLE = 1,
    Q3IDE_Q3IDE_ERROR_WINDOW_NOT_FOUND = 2,
    Q3IDE_Q3IDE_ERROR_PERMISSION_DENIED = 3,
    Q3IDE_Q3IDE_ERROR_ALREADY_CAPTURING = 4,
    Q3IDE_Q3IDE_ERROR_PLATFORM_ERROR = 5,
    Q3IDE_Q3IDE_ERROR_NULL_POINTER = 6,
} Q3ideQ3ideError;

/**
 * Opaque capture context handle passed across FFI.
 */
typedef struct Q3ideQ3ideCapture Q3ideQ3ideCapture;

/**
 * Window info returned to the engine for `/q3ide_list`.
 */
typedef struct Q3ideQ3ideWindowInfo {
    unsigned int window_id;
    /**
     * Null-terminated UTF-8 title string. Owned by the library.
     */
    const char *title;
    /**
     * Null-terminated UTF-8 app name string. Owned by the library.
     */
    const char *app_name;
    unsigned int width;
    unsigned int height;
    int is_on_screen;
} Q3ideQ3ideWindowInfo;

/**
 * Window list returned by `q3ide_list_windows`.
 */
typedef struct Q3ideQ3ideWindowList {
    const struct Q3ideQ3ideWindowInfo *windows;
    unsigned int count;
} Q3ideQ3ideWindowList;

/**
 * Frame data returned to the engine via C-ABI.
 */
typedef struct Q3ideQ3ideFrame {
    /**
     * Pointer to BGRA8 pixel data. Valid until next `q3ide_get_frame` call for this window.
     */
    const uint8_t *pixels;
    /**
     * Width in pixels.
     */
    unsigned int width;
    /**
     * Height in pixels.
     */
    unsigned int height;
    /**
     * Bytes per row (stride), may include padding.
     */
    unsigned int stride;
    /**
     * Frame timestamp in nanoseconds (monotonic).
     */
    uint64_t timestamp_ns;
    /**
     * Source window ID — the capture session that produced this frame.
     * Engine MUST verify this matches the requested window_id.
     */
    unsigned int source_wid;
} Q3ideQ3ideFrame;

/**
 * A single window change event.
 */
typedef struct Q3ideQ3ideWindowChange {
    unsigned int window_id;
    /**
     * Added/resized: heap-allocated null-terminated app name, freed by q3ide_free_change_list.
     * Removed: null.
     */
    char *app_name;
    unsigned int width;
    unsigned int height;
    /**
     * 1 = added, 0 = removed, 2 = resized, 3 = moved (composite crop updated internally).
     */
    int is_added;
} Q3ideQ3ideWindowChange;

/**
 * List of window changes since the last `q3ide_poll_window_changes` call.
 */
typedef struct Q3ideQ3ideWindowChangeList {
    struct Q3ideQ3ideWindowChange *changes;
    unsigned int count;
} Q3ideQ3ideWindowChangeList;

/**
 * Display info returned to the engine.
 */
typedef struct Q3ideQ3ideDisplayInfo {
    unsigned int display_id;
    unsigned int width;
    unsigned int height;
    int x;
    int y;
} Q3ideQ3ideDisplayInfo;

/**
 * Display list returned by `q3ide_list_displays`.
 */
typedef struct Q3ideQ3ideDisplayList {
    const struct Q3ideQ3ideDisplayInfo *displays;
    unsigned int count;
} Q3ideQ3ideDisplayList;

/**
 * CGPoint used for mouse event injection.
 */
typedef struct Q3ideCGPoint {
    double x;
    double y;
} Q3ideCGPoint;

extern bool sc_check_screen_recording_permission(void);

/**
 * Activate the app (PID) and try to unminimize its windows via AX.
 */
extern void sc_raise_window(int32_t pid);

/**
 * Initialize the capture system. Returns an opaque handle.
 * Returns NULL on failure (check stderr/logs for details).
 *
 * # Safety
 * Caller must eventually call `q3ide_shutdown` to free resources.
 */
q3ide_ struct Q3ideQ3ideCapture *q3ide_init(void);

/**
 * List available windows for capture.
 *
 * Returns a `Q3ideWindowList`. The caller must free it with `q3ide_free_window_list`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ struct Q3ideQ3ideWindowList q3ide_list_windows(struct Q3ideQ3ideCapture *handle);

/**
 * Free a window list returned by `q3ide_list_windows`.
 *
 * # Safety
 * `list` must have been returned by `q3ide_list_windows`.
 */
q3ide_ void q3ide_free_window_list(struct Q3ideQ3ideWindowList list);

/**
 * Start capturing a window by its ID.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
enum Q3ideQ3ideError q3ide_start_capture(struct Q3ideQ3ideCapture *handle,
                                         unsigned int window_id,
                                         int target_fps);

/**
 * Stop capturing a window.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ void q3ide_stop_capture(struct Q3ideQ3ideCapture *handle, unsigned int window_id);

/**
 * Get the latest captured frame for a window.
 *
 * Returns a `Q3ideFrame`. The pixel data pointer is valid until the next
 * call to `q3ide_get_frame` **for the same window_id**. Frames from
 * different windows do not invalidate each other.
 *
 * Returns a frame with `pixels = NULL` if no frame is available.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
struct Q3ideQ3ideFrame q3ide_get_frame(struct Q3ideQ3ideCapture *handle,
                                       unsigned int window_id);

/**
 * Shut down the capture system and free all resources.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 * After calling this, `handle` is invalid and must not be used.
 */
q3ide_ void q3ide_shutdown(struct Q3ideQ3ideCapture *handle);

/**
 * Get the formatted window list as a string for console display.
 * Returns a null-terminated string. Caller must free with `q3ide_free_string`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ char *q3ide_list_windows_formatted(struct Q3ideQ3ideCapture *handle);

/**
 * Free a string returned by `q3ide_list_windows_formatted`.
 *
 * # Safety
 * `s` must have been returned by a q3ide function that allocates strings.
 */
q3ide_ void q3ide_free_string(char *s);

/**
 * Poll for window open/close events since the last call.
 *
 * First call always returns an empty list and establishes the baseline snapshot.
 * Subsequent calls return diffs. Caller must free the list with `q3ide_free_change_list`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
struct Q3ideQ3ideWindowChangeList q3ide_poll_window_changes(struct Q3ideQ3ideCapture *handle);

/**
 * Free a change list returned by `q3ide_poll_window_changes`.
 *
 * # Safety
 * `list` must have been returned by `q3ide_poll_window_changes`.
 */
q3ide_ void q3ide_free_change_list(struct Q3ideQ3ideWindowChangeList list);

/**
 * Attach a window by title substring match.
 * Convenience for `/q3ide_attach <title>`.
 * Returns the window ID on success, 0 on failure.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 * `title_query` must be a valid null-terminated UTF-8 string.
 */
q3ide_
unsigned int q3ide_attach_by_title(struct Q3ideQ3ideCapture *handle,
                                   const char *title_query,
                                   int target_fps);

/**
 * List available displays.
 *
 * Returns a `Q3ideDisplayList`. The caller must free it with `q3ide_free_display_list`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ struct Q3ideQ3ideDisplayList q3ide_list_displays(struct Q3ideQ3ideCapture *handle);

/**
 * Free a display list returned by `q3ide_list_displays`.
 *
 * # Safety
 * `list` must have been returned by `q3ide_list_displays`.
 */
q3ide_ void q3ide_free_display_list(struct Q3ideQ3ideDisplayList list);

/**
 * Start capturing a single display by its CGDirectDisplayID.
 *
 * The display is captured independently — frames are keyed by display_id.
 * Use `q3ide_get_frame(handle, display_id)` to retrieve frames, and
 * `q3ide_stop_capture(handle, display_id)` to stop.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
enum Q3ideQ3ideError q3ide_start_display_capture(struct Q3ideQ3ideCapture *handle,
                                                 unsigned int display_id,
                                                 int target_fps);

extern void *CGEventCreateMouseEvent(void *source,
                                     uint32_t mouse_type,
                                     struct Q3ideCGPoint mouse_cursor_position,
                                     uint32_t mouse_button);

extern void *CGEventCreateKeyboardEvent(void *source, uint16_t virtual_key, uint8_t key_down);

extern void CGEventPost(uint32_t tap, void *event);

extern void CFRelease(void *cf);

/**
 * Inject a left mouse click at UV coordinates within a captured window.
 *
 * `uv_x` and `uv_y` are in [0.0, 1.0] relative to the window's content area.
 * The window's current screen bounds are looked up via ScreenCaptureKit.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
void q3ide_inject_click(struct Q3ideQ3ideCapture *_handle,
                        unsigned int window_id,
                        float uv_x,
                        float uv_y);

/**
 * Inject a keyboard key event into a captured window.
 *
 * `q3key` is a Q3 keycode (from keycodes.h). `is_down` is 1 for press, 0 for release.
 * Maps Q3 key codes to macOS CGKeyCode (ANSI layout).
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
void q3ide_inject_key(struct Q3ideQ3ideCapture *_handle,
                      unsigned int window_id,
                      int q3key,
                      int is_down);

/**
 * Activate and unminimize the macOS window behind the given capture ID.
 *
 * Looks up the window's owning application PID via SCK, then calls the Swift
 * `sc_raise_window(pid:)` helper which:
 *   1. Activates the app via NSRunningApplication (no special permission).
 *   2. Unminimizes all minimized windows via AX (requires Accessibility permission;
 *      silently skipped if not granted).
 *
 * Call this when the player hovers over a q3ide window (red border activates).
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ void q3ide_raise_window(struct Q3ideQ3ideCapture *handle, unsigned int window_id);

/**
 * Start capturing all displays, composited vertically into a single frame.
 *
 * All displays are scaled to the same width (max display width) while
 * maintaining aspect ratio, then stacked vertically.
 *
 * Returns the special Q3IDE_DESKTOP_CAPTURE_ID on success, 0 on failure.
 * Use this ID with q3ide_get_frame to retrieve composited frames.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ unsigned int q3ide_start_desktop_capture(struct Q3ideQ3ideCapture *handle, int target_fps);

#endif  /* Q3IDE_CAPTURE_H */
