/* q3ide_capture.h — Auto-generated by cbindgen. Do not edit. */

#ifndef Q3IDE_CAPTURE_H
#define Q3IDE_CAPTURE_H

/* WARNING: This file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Special window ID used for desktop capture (all displays composited).
 * Use this ID with q3ide_get_frame to retrieve the composited desktop frame.
 */
#define Q3ideQ3IDE_DESKTOP_CAPTURE_ID 4294967295

/**
 * Special window ID for desktop capture (all displays composited).
 */
#define Q3ideDESKTOP_CAPTURE_ID 4294967295

/**
 * Error codes returned by C-ABI functions.
 */
typedef enum Q3ideQ3ideError {
    Q3IDE_Q3IDE_ERROR_OK = 0,
    Q3IDE_Q3IDE_ERROR_NOT_AVAILABLE = 1,
    Q3IDE_Q3IDE_ERROR_WINDOW_NOT_FOUND = 2,
    Q3IDE_Q3IDE_ERROR_PERMISSION_DENIED = 3,
    Q3IDE_Q3IDE_ERROR_ALREADY_CAPTURING = 4,
    Q3IDE_Q3IDE_ERROR_PLATFORM_ERROR = 5,
    Q3IDE_Q3IDE_ERROR_NULL_POINTER = 6,
} Q3ideQ3ideError;

/**
 * Opaque capture context handle passed across FFI.
 */
typedef struct Q3ideQ3ideCapture Q3ideQ3ideCapture;

/**
 * Window info returned to the engine for `/q3ide_list`.
 */
typedef struct Q3ideQ3ideWindowInfo {
    unsigned int window_id;
    /**
     * Null-terminated UTF-8 title string. Owned by the library.
     */
    const char *title;
    /**
     * Null-terminated UTF-8 app name string. Owned by the library.
     */
    const char *app_name;
    unsigned int width;
    unsigned int height;
    int is_on_screen;
} Q3ideQ3ideWindowInfo;

/**
 * Window list returned by `q3ide_list_windows`.
 */
typedef struct Q3ideQ3ideWindowList {
    const struct Q3ideQ3ideWindowInfo *windows;
    unsigned int count;
} Q3ideQ3ideWindowList;

/**
 * Frame data returned to the engine via C-ABI.
 */
typedef struct Q3ideQ3ideFrame {
    /**
     * Pointer to BGRA8 pixel data. Valid until next `q3ide_get_frame` call for this window.
     */
    const uint8_t *pixels;
    /**
     * Width in pixels.
     */
    unsigned int width;
    /**
     * Height in pixels.
     */
    unsigned int height;
    /**
     * Bytes per row (stride), may include padding.
     */
    unsigned int stride;
    /**
     * Frame timestamp in nanoseconds (monotonic).
     */
    uint64_t timestamp_ns;
    /**
     * Source window ID — the capture session that produced this frame.
     * Engine MUST verify this matches the requested window_id.
     */
    unsigned int source_wid;
} Q3ideQ3ideFrame;

/**
 * Display info returned to the engine.
 */
typedef struct Q3ideQ3ideDisplayInfo {
    unsigned int display_id;
    unsigned int width;
    unsigned int height;
    int x;
    int y;
} Q3ideQ3ideDisplayInfo;

/**
 * Display list returned by `q3ide_list_displays`.
 */
typedef struct Q3ideQ3ideDisplayList {
    const struct Q3ideQ3ideDisplayInfo *displays;
    unsigned int count;
} Q3ideQ3ideDisplayList;

/**
 * Initialize the capture system. Returns an opaque handle.
 * Returns NULL on failure (check stderr/logs for details).
 *
 * # Safety
 * Caller must eventually call `q3ide_shutdown` to free resources.
 */
q3ide_ struct Q3ideQ3ideCapture *q3ide_init(void);

/**
 * List available windows for capture.
 *
 * Returns a `Q3ideWindowList`. The caller must free it with `q3ide_free_window_list`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ struct Q3ideQ3ideWindowList q3ide_list_windows(struct Q3ideQ3ideCapture *handle);

/**
 * Free a window list returned by `q3ide_list_windows`.
 *
 * # Safety
 * `list` must have been returned by `q3ide_list_windows`.
 */
q3ide_ void q3ide_free_window_list(struct Q3ideQ3ideWindowList list);

/**
 * Start capturing a window by its ID.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
enum Q3ideQ3ideError q3ide_start_capture(struct Q3ideQ3ideCapture *handle,
                                         unsigned int window_id,
                                         unsigned int target_fps);

/**
 * Stop capturing a window.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ void q3ide_stop_capture(struct Q3ideQ3ideCapture *handle, unsigned int window_id);

/**
 * Get the latest captured frame for a window.
 *
 * Returns a `Q3ideFrame`. The pixel data pointer is valid until the next
 * call to `q3ide_get_frame` **for the same window_id**. Frames from
 * different windows do not invalidate each other.
 *
 * Returns a frame with `pixels = NULL` if no frame is available.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
struct Q3ideQ3ideFrame q3ide_get_frame(struct Q3ideQ3ideCapture *handle,
                                       unsigned int window_id);

/**
 * Shut down the capture system and free all resources.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 * After calling this, `handle` is invalid and must not be used.
 */
q3ide_ void q3ide_shutdown(struct Q3ideQ3ideCapture *handle);

/**
 * Get the formatted window list as a string for console display.
 * Returns a null-terminated string. Caller must free with `q3ide_free_string`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ char *q3ide_list_windows_formatted(struct Q3ideQ3ideCapture *handle);

/**
 * Free a string returned by `q3ide_list_windows_formatted`.
 *
 * # Safety
 * `s` must have been returned by a q3ide function that allocates strings.
 */
q3ide_ void q3ide_free_string(char *s);

/**
 * Attach a window by title substring match.
 * Convenience for `/q3ide_attach <title>`.
 * Returns the window ID on success, 0 on failure.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 * `title_query` must be a valid null-terminated UTF-8 string.
 */
q3ide_
unsigned int q3ide_attach_by_title(struct Q3ideQ3ideCapture *handle,
                                   const char *title_query,
                                   unsigned int target_fps);

/**
 * List available displays.
 *
 * Returns a `Q3ideDisplayList`. The caller must free it with `q3ide_free_display_list`.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_ struct Q3ideQ3ideDisplayList q3ide_list_displays(struct Q3ideQ3ideCapture *handle);

/**
 * Free a display list returned by `q3ide_list_displays`.
 *
 * # Safety
 * `list` must have been returned by `q3ide_list_displays`.
 */
q3ide_ void q3ide_free_display_list(struct Q3ideQ3ideDisplayList list);

/**
 * Start capturing a single display by its CGDirectDisplayID.
 *
 * The display is captured independently — frames are keyed by display_id.
 * Use `q3ide_get_frame(handle, display_id)` to retrieve frames, and
 * `q3ide_stop_capture(handle, display_id)` to stop.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
enum Q3ideQ3ideError q3ide_start_display_capture(struct Q3ideQ3ideCapture *handle,
                                                 unsigned int display_id,
                                                 unsigned int target_fps);

/**
 * Start capturing all displays, composited vertically into a single frame.
 *
 * All displays are scaled to the same width (max display width) while
 * maintaining aspect ratio, then stacked vertically.
 *
 * Returns the special Q3IDE_DESKTOP_CAPTURE_ID on success, 0 on failure.
 * Use this ID with q3ide_get_frame to retrieve composited frames.
 *
 * # Safety
 * `handle` must be a valid pointer from `q3ide_init`.
 */
q3ide_
unsigned int q3ide_start_desktop_capture(struct Q3ideQ3ideCapture *handle,
                                         unsigned int target_fps);

#endif  /* Q3IDE_CAPTURE_H */
